#!/bin/sh
HA_URL="http://100.91.124.23:8123"
EXT_DIR="$HOME/.config/chromium/hide-cursor-extension"

# Wait up to 60s for HA to be reachable before opening Chromium
i=0
while [ $i -lt 60 ]; do
  curl -fsSL --connect-timeout 2 --max-time 4 -o /dev/null "$HA_URL" 2>/dev/null && break
  sleep 1
  i=$((i + 1))
done

exec chromium \
  --enable-remote-extensions \
  --enable-wayland-ime \
  --wayland-text-input-version=3 \
  --force-dark-mode \
  --enable-features=WebContentsForceDark \
  --disable-extensions-except="$EXT_DIR" \
  --load-extension="$EXT_DIR" \
  --kiosk \
  --noerrdialogs \
  --disable-infobars \
  --no-first-run \
  --disable-features=ChromeWhatsNewUI,PrivacySandboxSettings4,Translate \
  --overscroll-history-navigation=0 \
  --disable-sync \
  --no-default-browser-check \
  --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' \
  --touch-events=enabled \
  --ozone-platform=wayland \
  "${HA_URL}/desktop-tablet"
